version: '3'

services:
  app:
    image: "ethan01/url-shortener-app:v1.0.0"
    build: .
    ports:
      - "9808:9808"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379  # 这里使用 Redis 服务的名称

  redis:
    image: "redis:latest"
    # ports:
    #   - "6379:6379"
